### ISSUE TITLE
Generate BOM

### ISSUE THREAD

**Issue by mizdebsk** [msimacek/java-deptools#1]
I just had an idea - java-deptools could generate BOM file (bill of materials) for all packages in package collection. BOM is just a Maven POM file which in its dependencyManagement section would list all artifacts provided in given collection (Fedora version).

Use cases:
- for developers who want to develop software easily packageable; they would use artifacts from Maven Central, but versions which are available in Fedora, resulting in project that is easy to package - wouldn't require patching,
- for packagers to help debugging packaging problems by using upstream binaries with versions matching Fedora versions.

Implementation shouldn't be difficult - java-deptools already opens all Java RPMs, it would just need to extract info about provided artifacts from Maven metadata and output that info as XML file. (At first I thought about writing a custom script to generate BOM from YUM metadata, but then I realized that version we put in provides is transformed, for example dashes are replaced with dots.)

**Comment by msimacek** [comment]
Sounds reasonable. How should the BOM be published?

**Comment by mizdebsk** [comment]
There is no interest in this feature, so I'm closing it for now. Please reopen and add a comment if you would like to see this feature.
